### ISSUE TITLE
What's the difference compared to docsify-katex

### ISSUE THREAD

**Issue by zyzbj** [scruel/docsify-latex#2]
我在寻找 docsify 插件时注意到了这个项目，感谢您的贡献！

同时，我也找到了功能相近的 docsify 插件：[docsify-katex | GitHub](https://github.com/upupming/docsify-katex)

请问，本项目和 docsify-katex 有什么不同之处？
在功能上有什么创新，以及有哪些优化的地方？谢谢

**Comment by scruel** [comment]
你好，这是个人写的小项目，主要用于解析我的相关[笔记项目](https://scruel.github.io/Notes-ML-AndrewNg/)
1. 本项目的解析方式不同于 docsify-katex，只使用了 docsify 提供的官方接口，故不会有奇怪的问题，后续跟随官方升级应该也比较方便。
2. 相较于只支持 katex，本项目同时支持 katex、mathjax，如果后续有其他的三方解析也可以很方便地集成。
3. 我基于个人的笔记项目，对本项目做了大量的测试，可以解析诸如 `\$ $x^2$` 等我个人笔记中的复杂公式块
（本项目也正是因为测试发现 docsify-katex 无法解析的很好才做的 ）

目前已经趋于稳定，准备着手写一下说明文档，现在要用的话，可以参考一下上面提到的笔记项目，这个 issue 会在文档完成后关闭，欢迎尝试使用 😆。

**Comment by scruel** [comment]
你好，这是个人写的小项目，主要用于解析我的相关[笔记项目](https://scruel.github.io/Notes-ML-AndrewNg/)
1. 本项目的解析方式不同于 docsify-katex，只使用了 docsify 提供的官方接口，故不会有奇怪的问题，后续跟随官方升级应该也比较方便。
2. 相较于只支持 katex，本项目同时支持 katex、mathjax（包括 V2 和 V3），如果后续有其他的三方解析也可以很方便地集成。
3. 我基于个人的笔记项目，对本项目做了大量的测试，可以解析诸如 `\$ $x^2$` 等我个人笔记中的复杂公式块
（本项目也正是因为测试发现 docsify-katex 无法解析的很好才做的 ）

目前已经趋于稳定，准备着手写一下说明文档，现在要用的话，可以参考一下上面提到的笔记项目，这个 issue 会在文档完成后关闭，欢迎尝试使用 😆。

**Comment by scruel** [comment]
你好，这是个人写的小项目，主要用于解析我的相关[笔记项目](https://scruel.github.io/Notes-ML-AndrewNg/)
1. docsify-katex 看新版本是需要为页面引入 marked 组件，本项目暂不需要，是自己根据情况写的解析（markdown 解析属实是一个头疼的事）。
2. 相较于只支持 katex，本项目同时支持 katex、mathjax（包括 V2 和 V3），如果后续有其他的三方解析也可以很方便地集成。
3. 奇怪的问题可能相较于 docsify-katex 少一些，因为在对渲染个人笔记进行支持的过程中做了大量测试，也发现 docsify 本身的一些问题，同时给他们提了一些 issues。
4. 包含了一些有用的辅助功能。

说到底，主要是为了支持 MathJax 来解析个人笔记，笔记内有诸如 `\$ $x^2$` 等较为复杂的文本，这个点上尝试过一些集成MathJax 的 workaround，发现都无法正确处理，而后也尝试过使用 docsify-katex，但 katex 的部分解析和 MathJax 不一样，发现还是有一些小问题，最后才有了本项目。

**Comment by scruel** [comment]
@zyzbj 文档已完成，https://scruel.github.io/docsify-latex/

**Comment by scruel** [comment]
文档已完成，https://scruel.github.io/docsify-latex/
